name: Pull request pipeline

on:
  pull_request:
    branches:
      - main
      - develop

jobs:
  build_and_test:
    name: Rust shortenurl project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          
      - name: Build Docker image
        run: docker build -t registry.heroku.com/${{ secrets.HEROKU_APP }}/web:latest .

      - name: Docker image info
        run: docker images
